### ISSUE TITLE
I have an Android connection VPN code. After binding, if there is no connection status event, can you bind it for me?

### ISSUE THREAD

**Issue by bbhxwl** [Laerdal/Laerdal.Xamarin.FFmpeg.iOS#1]
I have an Android connection VPN code. After binding, if there is no connection status event, can you bind it for me?

**Comment by framinosona** [comment]
Hi @bbhxwl,

Could you explain? What does it have to do with FFmpeg.iOS ? 

Also, the Binding code is here visible for all to be able to Learn and grow together as a community. Xamarin being very transparent, I think it's just fair to make these binding libraries' code available too.

Feel free to report bugs to make a better FFmpeg Binding library, to suggest improvements or send pull-requests.
